
// Author     KMS - Martin Dubois, ing.
// Copyright  (C) 2019 KMS. All rights reserved.
// Product    GPU-dpi
// File       GPU_dpi_Test/OpenNet_Test.cpp

// Includes
/////////////////////////////////////////////////////////////////////////////

#include "Component.h"

// Tests
/////////////////////////////////////////////////////////////////////////////

// Setup A  At least one OpenNet adapter
// Setup B  At least one OpenNet adapter receiving trafic generated by
//          GPU-dpi_TG using the test folder
KMS_TEST_GROUP_LIST_BEGIN
    KMS_TEST_GROUP_LIST_ENTRY("Base"   )
    KMS_TEST_GROUP_LIST_ENTRY("Display")
    KMS_TEST_GROUP_LIST_ENTRY("SetupA" )
    KMS_TEST_GROUP_LIST_ENTRY("SetupB" )
KMS_TEST_GROUP_LIST_END

extern int Filter_SetupB ();

extern int SetupTool_Base();

extern int System_Base   ();
extern int System_Display();
extern int System_SetupA ();

KMS_TEST_LIST_BEGIN
    KMS_TEST_LIST_ENTRY(Filter_SetupB , "Filter - Setup B", 3, KMS_TEST_FLAG_INTERACTION_NEEDED)
    KMS_TEST_LIST_ENTRY(SetupTool_Base, "SetupTool - Base", 0, 0)
    KMS_TEST_LIST_ENTRY(System_Base   , "System - Base"   , 0, 0)
    KMS_TEST_LIST_ENTRY(System_Display, "System - Display", 1, KMS_TEST_FLAG_INTERACTION_NEEDED)
    KMS_TEST_LIST_ENTRY(System_SetupA , "System - SetupA" , 2, KMS_TEST_FLAG_INTERACTION_NEEDED)
KMS_TEST_LIST_END

KMS_TEST_MAIN
